INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (0, "Walther Spellacey", 111111111, "USA");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (0, 0);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (1, "Hubie Bywater", 111112567, "Costa Rica");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (1, 1);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (2, "Farra Mundford", 111114023, "Mexico");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (2, 2);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (3, "Rancell Alabaster", 111115479, "Espana");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (3, 3);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (4, "Thedric Commusso", 111116935, "Canada");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (4, 4);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (5, "Quill Warlton", 111118391, "Alemania");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (5, 5);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (6, "Sofie Malacrida", 111119847, "Reino Unido");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (6, 6);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (7, "Gusti McNysche", 111121303, "Japon");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (7, 7);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (8, "Jerrie Goady", 111122759, "Corea");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (8, 8);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (9, "Giustina Mee", 111124215, "Suiza");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (9, 9);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (10, "Jule Borrows", 111125671, "USA");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (10, 10);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (11, "Lucille Bentzen", 111127127, "Costa Rica");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (11, 11);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (12, "Karoline De Simoni", 111128583, "Mexico");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (12, 12);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (13, "Arel Rappoport", 111130039, "Espana");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (13, 13);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (14, "Alfredo McMurthy", 111131495, "Canada");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (14, 14);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (15, "Dorry Caldow", 111132951, "Alemania");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (15, 15);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (16, "Reinaldo Lush", 111134407, "Reino Unido");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (16, 16);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (17, "Janeen Kingsley", 111135863, "Japon");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (17, 17);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (18, "Alameda Beale", 111137319, "Corea");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (18, 18);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (19, "Babette O'Scannill", 111138775, "Suiza");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (19, 19);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (20, "Flora Girauld", 111140231, "Costa Rica");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (20, 20);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (21, "Abbe Fransewich", 111141687, "Mexico");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (21, 21);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (22, "Abbie Breeze", 111143143, "Espana");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (22, 22);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (23, "Becka Haddy", 111144599, "Canada");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (23, 23);
INSERT INTO `iot`.`cliente` (`idcliente`,`nombre`,`cedula`,`localizacion`) VALUES (24, "Brinn Nizet", 111146055, "Alemania");
INSERT INTO `iot`.`casa` (`idcasa`,`idcliente`) VALUES (24, 24);
