INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (0, "producto0", 7699, "Dispositivo IOT numero 0", "Manual cod.0", "https://iothome.com/producto0", "Info adicional del producto0", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (0, 496, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (1, "producto1", 882, "Dispositivo IOT numero 1", "Manual cod.1", "https://iothome.com/producto1", "Info adicional del producto1", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (1, 907, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (2, "producto2", 1145, "Dispositivo IOT numero 2", "Manual cod.2", "https://iothome.com/producto2", "Info adicional del producto2", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (2, 993, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (3, "producto3", 4179, "Dispositivo IOT numero 3", "Manual cod.3", "https://iothome.com/producto3", "Info adicional del producto3", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (3, 402, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (4, "producto4", 9591, "Dispositivo IOT numero 4", "Manual cod.4", "https://iothome.com/producto4", "Info adicional del producto4", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (4, 785, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (5, "producto5", 709, "Dispositivo IOT numero 5", "Manual cod.5", "https://iothome.com/producto5", "Info adicional del producto5", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (5, 895, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (6, "producto6", 4565, "Dispositivo IOT numero 6", "Manual cod.6", "https://iothome.com/producto6", "Info adicional del producto6", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (6, 207, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (7, "producto7", 9271, "Dispositivo IOT numero 7", "Manual cod.7", "https://iothome.com/producto7", "Info adicional del producto7", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (7, 220, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (8, "producto8", 3230, "Dispositivo IOT numero 8", "Manual cod.8", "https://iothome.com/producto8", "Info adicional del producto8", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (8, 548, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (9, "producto9", 4977, "Dispositivo IOT numero 9", "Manual cod.9", "https://iothome.com/producto9", "Info adicional del producto9", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (9, 215, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (10, "producto10", 2231, "Dispositivo IOT numero 10", "Manual cod.10", "https://iothome.com/producto10", "Info adicional del producto10", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (10, 524, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (11, "producto11", 5630, "Dispositivo IOT numero 11", "Manual cod.11", "https://iothome.com/producto11", "Info adicional del producto11", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (11, 873, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (12, "producto12", 5477, "Dispositivo IOT numero 12", "Manual cod.12", "https://iothome.com/producto12", "Info adicional del producto12", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (12, 677, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (13, "producto13", 3815, "Dispositivo IOT numero 13", "Manual cod.13", "https://iothome.com/producto13", "Info adicional del producto13", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (13, 582, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (14, "producto14", 9174, "Dispositivo IOT numero 14", "Manual cod.14", "https://iothome.com/producto14", "Info adicional del producto14", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (14, 117, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (15, "producto15", 9872, "Dispositivo IOT numero 15", "Manual cod.15", "https://iothome.com/producto15", "Info adicional del producto15", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (15, 961, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (16, "producto16", 7647, "Dispositivo IOT numero 16", "Manual cod.16", "https://iothome.com/producto16", "Info adicional del producto16", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (16, 263, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (17, "producto17", 7663, "Dispositivo IOT numero 17", "Manual cod.17", "https://iothome.com/producto17", "Info adicional del producto17", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (17, 329, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (18, "producto18", 2026, "Dispositivo IOT numero 18", "Manual cod.18", "https://iothome.com/producto18", "Info adicional del producto18", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (18, 701, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (19, "producto19", 3124, "Dispositivo IOT numero 19", "Manual cod.19", "https://iothome.com/producto19", "Info adicional del producto19", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (19, 722, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (20, "producto20", 64, "Dispositivo IOT numero 20", "Manual cod.20", "https://iothome.com/producto20", "Info adicional del producto20", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (20, 167, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (21, "producto21", 4032, "Dispositivo IOT numero 21", "Manual cod.21", "https://iothome.com/producto21", "Info adicional del producto21", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (21, 386, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (22, "producto22", 3884, "Dispositivo IOT numero 22", "Manual cod.22", "https://iothome.com/producto22", "Info adicional del producto22", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (22, 714, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (23, "producto23", 3864, "Dispositivo IOT numero 23", "Manual cod.23", "https://iothome.com/producto23", "Info adicional del producto23", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (23, 132, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (24, "producto24", 8616, "Dispositivo IOT numero 24", "Manual cod.24", "https://iothome.com/producto24", "Info adicional del producto24", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (24, 877, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (25, "producto25", 581, "Dispositivo IOT numero 25", "Manual cod.25", "https://iothome.com/producto25", "Info adicional del producto25", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (25, 823, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (26, "producto26", 8160, "Dispositivo IOT numero 26", "Manual cod.26", "https://iothome.com/producto26", "Info adicional del producto26", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (26, 159, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (27, "producto27", 30, "Dispositivo IOT numero 27", "Manual cod.27", "https://iothome.com/producto27", "Info adicional del producto27", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (27, 877, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (28, "producto28", 7079, "Dispositivo IOT numero 28", "Manual cod.28", "https://iothome.com/producto28", "Info adicional del producto28", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (28, 825, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (29, "producto29", 3331, "Dispositivo IOT numero 29", "Manual cod.29", "https://iothome.com/producto29", "Info adicional del producto29", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (29, 999, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (30, "producto30", 9200, "Dispositivo IOT numero 30", "Manual cod.30", "https://iothome.com/producto30", "Info adicional del producto30", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (30, 156, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (31, "producto31", 2798, "Dispositivo IOT numero 31", "Manual cod.31", "https://iothome.com/producto31", "Info adicional del producto31", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (31, 686, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (32, "producto32", 7829, "Dispositivo IOT numero 32", "Manual cod.32", "https://iothome.com/producto32", "Info adicional del producto32", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (32, 711, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (33, "producto33", 6836, "Dispositivo IOT numero 33", "Manual cod.33", "https://iothome.com/producto33", "Info adicional del producto33", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (33, 145, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (34, "producto34", 1761, "Dispositivo IOT numero 34", "Manual cod.34", "https://iothome.com/producto34", "Info adicional del producto34", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (34, 617, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (35, "producto35", 663, "Dispositivo IOT numero 35", "Manual cod.35", "https://iothome.com/producto35", "Info adicional del producto35", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (35, 174, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (36, "producto36", 5821, "Dispositivo IOT numero 36", "Manual cod.36", "https://iothome.com/producto36", "Info adicional del producto36", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (36, 951, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (37, "producto37", 2504, "Dispositivo IOT numero 37", "Manual cod.37", "https://iothome.com/producto37", "Info adicional del producto37", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (37, 235, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (38, "producto38", 4612, "Dispositivo IOT numero 38", "Manual cod.38", "https://iothome.com/producto38", "Info adicional del producto38", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (38, 149, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (39, "producto39", 1662, "Dispositivo IOT numero 39", "Manual cod.39", "https://iothome.com/producto39", "Info adicional del producto39", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (39, 500, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (40, "producto40", 2224, "Dispositivo IOT numero 40", "Manual cod.40", "https://iothome.com/producto40", "Info adicional del producto40", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (40, 981, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (41, "producto41", 3597, "Dispositivo IOT numero 41", "Manual cod.41", "https://iothome.com/producto41", "Info adicional del producto41", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (41, 656, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (42, "producto42", 1802, "Dispositivo IOT numero 42", "Manual cod.42", "https://iothome.com/producto42", "Info adicional del producto42", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (42, 722, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (43, "producto43", 959, "Dispositivo IOT numero 43", "Manual cod.43", "https://iothome.com/producto43", "Info adicional del producto43", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (43, 644, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (44, "producto44", 1826, "Dispositivo IOT numero 44", "Manual cod.44", "https://iothome.com/producto44", "Info adicional del producto44", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (44, 473, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (45, "producto45", 6345, "Dispositivo IOT numero 45", "Manual cod.45", "https://iothome.com/producto45", "Info adicional del producto45", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (45, 491, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (46, "producto46", 9113, "Dispositivo IOT numero 46", "Manual cod.46", "https://iothome.com/producto46", "Info adicional del producto46", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (46, 332, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (47, "producto47", 3401, "Dispositivo IOT numero 47", "Manual cod.47", "https://iothome.com/producto47", "Info adicional del producto47", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (47, 867, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (48, "producto48", 2227, "Dispositivo IOT numero 48", "Manual cod.48", "https://iothome.com/producto48", "Info adicional del producto48", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (48, 777, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (49, "producto49", 8396, "Dispositivo IOT numero 49", "Manual cod.49", "https://iothome.com/producto49", "Info adicional del producto49", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (49, 685, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (50, "producto50", 5934, "Dispositivo IOT numero 50", "Manual cod.50", "https://iothome.com/producto50", "Info adicional del producto50", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (50, 786, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (51, "producto51", 5024, "Dispositivo IOT numero 51", "Manual cod.51", "https://iothome.com/producto51", "Info adicional del producto51", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (51, 170, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (52, "producto52", 1358, "Dispositivo IOT numero 52", "Manual cod.52", "https://iothome.com/producto52", "Info adicional del producto52", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (52, 497, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (53, "producto53", 7112, "Dispositivo IOT numero 53", "Manual cod.53", "https://iothome.com/producto53", "Info adicional del producto53", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (53, 335, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (54, "producto54", 318, "Dispositivo IOT numero 54", "Manual cod.54", "https://iothome.com/producto54", "Info adicional del producto54", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (54, 582, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (55, "producto55", 2135, "Dispositivo IOT numero 55", "Manual cod.55", "https://iothome.com/producto55", "Info adicional del producto55", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (55, 236, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (56, "producto56", 3952, "Dispositivo IOT numero 56", "Manual cod.56", "https://iothome.com/producto56", "Info adicional del producto56", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (56, 921, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (57, "producto57", 4109, "Dispositivo IOT numero 57", "Manual cod.57", "https://iothome.com/producto57", "Info adicional del producto57", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (57, 114, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (58, "producto58", 677, "Dispositivo IOT numero 58", "Manual cod.58", "https://iothome.com/producto58", "Info adicional del producto58", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (58, 668, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (59, "producto59", 7368, "Dispositivo IOT numero 59", "Manual cod.59", "https://iothome.com/producto59", "Info adicional del producto59", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (59, 571, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (60, "producto60", 9121, "Dispositivo IOT numero 60", "Manual cod.60", "https://iothome.com/producto60", "Info adicional del producto60", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (60, 910, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (61, "producto61", 6576, "Dispositivo IOT numero 61", "Manual cod.61", "https://iothome.com/producto61", "Info adicional del producto61", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (61, 957, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (62, "producto62", 8567, "Dispositivo IOT numero 62", "Manual cod.62", "https://iothome.com/producto62", "Info adicional del producto62", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (62, 434, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (63, "producto63", 8871, "Dispositivo IOT numero 63", "Manual cod.63", "https://iothome.com/producto63", "Info adicional del producto63", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (63, 510, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (64, "producto64", 7811, "Dispositivo IOT numero 64", "Manual cod.64", "https://iothome.com/producto64", "Info adicional del producto64", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (64, 137, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (65, "producto65", 9958, "Dispositivo IOT numero 65", "Manual cod.65", "https://iothome.com/producto65", "Info adicional del producto65", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (65, 643, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (66, "producto66", 9232, "Dispositivo IOT numero 66", "Manual cod.66", "https://iothome.com/producto66", "Info adicional del producto66", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (66, 240, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (67, "producto67", 3752, "Dispositivo IOT numero 67", "Manual cod.67", "https://iothome.com/producto67", "Info adicional del producto67", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (67, 947, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (68, "producto68", 2726, "Dispositivo IOT numero 68", "Manual cod.68", "https://iothome.com/producto68", "Info adicional del producto68", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (68, 130, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (69, "producto69", 4722, "Dispositivo IOT numero 69", "Manual cod.69", "https://iothome.com/producto69", "Info adicional del producto69", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (69, 445, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (70, "producto70", 3717, "Dispositivo IOT numero 70", "Manual cod.70", "https://iothome.com/producto70", "Info adicional del producto70", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (70, 900, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (71, "producto71", 250, "Dispositivo IOT numero 71", "Manual cod.71", "https://iothome.com/producto71", "Info adicional del producto71", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (71, 639, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (72, "producto72", 6025, "Dispositivo IOT numero 72", "Manual cod.72", "https://iothome.com/producto72", "Info adicional del producto72", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (72, 258, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (73, "producto73", 4344, "Dispositivo IOT numero 73", "Manual cod.73", "https://iothome.com/producto73", "Info adicional del producto73", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (73, 890, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (74, "producto74", 6844, "Dispositivo IOT numero 74", "Manual cod.74", "https://iothome.com/producto74", "Info adicional del producto74", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (74, 531, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (75, "producto75", 4397, "Dispositivo IOT numero 75", "Manual cod.75", "https://iothome.com/producto75", "Info adicional del producto75", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (75, 114, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (76, "producto76", 1081, "Dispositivo IOT numero 76", "Manual cod.76", "https://iothome.com/producto76", "Info adicional del producto76", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (76, 826, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (77, "producto77", 4705, "Dispositivo IOT numero 77", "Manual cod.77", "https://iothome.com/producto77", "Info adicional del producto77", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (77, 234, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (78, "producto78", 5900, "Dispositivo IOT numero 78", "Manual cod.78", "https://iothome.com/producto78", "Info adicional del producto78", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (78, 989, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (79, "producto79", 9216, "Dispositivo IOT numero 79", "Manual cod.79", "https://iothome.com/producto79", "Info adicional del producto79", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (79, 730, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (80, "producto80", 174, "Dispositivo IOT numero 80", "Manual cod.80", "https://iothome.com/producto80", "Info adicional del producto80", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (80, 873, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (81, "producto81", 3078, "Dispositivo IOT numero 81", "Manual cod.81", "https://iothome.com/producto81", "Info adicional del producto81", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (81, 210, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (82, "producto82", 4583, "Dispositivo IOT numero 82", "Manual cod.82", "https://iothome.com/producto82", "Info adicional del producto82", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (82, 549, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (83, "producto83", 409, "Dispositivo IOT numero 83", "Manual cod.83", "https://iothome.com/producto83", "Info adicional del producto83", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (83, 108, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (84, "producto84", 6162, "Dispositivo IOT numero 84", "Manual cod.84", "https://iothome.com/producto84", "Info adicional del producto84", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (84, 542, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (85, "producto85", 8699, "Dispositivo IOT numero 85", "Manual cod.85", "https://iothome.com/producto85", "Info adicional del producto85", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (85, 218, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (86, "producto86", 4650, "Dispositivo IOT numero 86", "Manual cod.86", "https://iothome.com/producto86", "Info adicional del producto86", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (86, 648, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (87, "producto87", 3188, "Dispositivo IOT numero 87", "Manual cod.87", "https://iothome.com/producto87", "Info adicional del producto87", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (87, 408, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (88, "producto88", 9436, "Dispositivo IOT numero 88", "Manual cod.88", "https://iothome.com/producto88", "Info adicional del producto88", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (88, 947, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (89, "producto89", 8350, "Dispositivo IOT numero 89", "Manual cod.89", "https://iothome.com/producto89", "Info adicional del producto89", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (89, 956, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (90, "producto90", 8548, "Dispositivo IOT numero 90", "Manual cod.90", "https://iothome.com/producto90", "Info adicional del producto90", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (90, 379, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (91, "producto91", 7249, "Dispositivo IOT numero 91", "Manual cod.91", "https://iothome.com/producto91", "Info adicional del producto91", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (91, 162, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (92, "producto92", 2856, "Dispositivo IOT numero 92", "Manual cod.92", "https://iothome.com/producto92", "Info adicional del producto92", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (92, 337, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (93, "producto93", 6974, "Dispositivo IOT numero 93", "Manual cod.93", "https://iothome.com/producto93", "Info adicional del producto93", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (93, 980, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (94, "producto94", 7581, "Dispositivo IOT numero 94", "Manual cod.94", "https://iothome.com/producto94", "Info adicional del producto94", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (94, 304, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (95, "producto95", 9145, "Dispositivo IOT numero 95", "Manual cod.95", "https://iothome.com/producto95", "Info adicional del producto95", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (95, 998, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (96, "producto96", 3979, "Dispositivo IOT numero 96", "Manual cod.96", "https://iothome.com/producto96", "Info adicional del producto96", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (96, 616, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (97, "producto97", 6161, "Dispositivo IOT numero 97", "Manual cod.97", "https://iothome.com/producto97", "Info adicional del producto97", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (97, 504, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (98, "producto98", 3327, "Dispositivo IOT numero 98", "Manual cod.98", "https://iothome.com/producto98", "Info adicional del producto98", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (98, 339, "2011-01-01 00:00:00");
INSERT INTO `produccion`.`productos` (idproductos, nombre, numero_parte, descripcion, manual,archivos_digitales, info_adicional, cantidad)VALUES (99, "producto99", 7514, "Dispositivo IOT numero 99", "Manual cod.99", "https://iothome.com/producto99", "Info adicional del producto99", 0);
INSERT INTO `produccion`.`precios` (idproductos, precio, fecha) VALUES (99, 925, "2011-01-01 00:00:00");
